### ISSUE TITLE
Get file from server

### ISSUE THREAD

**Issue by whuiras** [mechaftp/MechaFTP#8]
Class for getting files from the server. Should take in a relative or absolute file path. File should be placed in user's ~/Downloads folder

- [ ] Get file function
- [ ] Log activity
- [ ] Unit test that confirms file is correctly downloaded from mock server

**Comment by snakevirgo** [comment]
it says issue-8 branch already exists, so I made my issue_8 branch (with an underscore instead of a hyphen). Hope that's ok.
